# Classes

# datagov.jl or dg.jl
jl_path: ./test_file.jl
#jl_path: ./downloaded_data/datasets/dg_all.jl
data_path: ./data/
model_path: ./results/
dataset: dg
#dataset: dg
seed: 0
num_of_folds: 5
fold_file: folds.txt

c2v:
    cell_classifier_model_file: cell_classify_model
    block_extractor_model_file: block_extract_model
    cc_output: c2v_cc_predictions.json
    be_output: c2v_be_predictions.json
    ce_model: './models/ce.model'
    fe_model: './models/fe.model'
    cl_model: './models/cl.model'
    w2v: './models/glove.840B.300d.txt'
    infersent_model: './models/infersent1.pkl'
    vocab_size: 60000


psl:
    cc_output: psl_cc_predictions.json
    be_output: psl_be_predictions.json
    lp_output: psl_lp_predictions.json
    num_process: 50
    num_tree: 50

#crf:
#    cell_classifier_model_file: grid_crf_cell_classify_model
#    block_extractor_model_file: chain_crf_block_extract_model
#    layout_predictor_model_file: crf_layout_predictor_model
#    lp_output: crf_lp_predictions.json
#    cc_output: crf_cc_predictions.json
#    be_output: crf_be_predictions.json
#
#mlp:
#    cell_classifier_model_file: mlp_cell_classify_model
#    cc_output: mlp_cc_predictions.json
#

rf:
    layout_predictor_model_file: rf_layout_predictor_model
    lp_output: rf_lp_predictions.json

cell_classifier:
    rule_file: ./cell_classifier/psl/psl-cell-classifier.psl
    learned_rule_file: ./cell_classifier/psl/psl-cell-classifier.psl
    predicate_file: ./cell_classifier/psl/psl-cell-classifier-predicates.txt
    learn_path: ./data/psl/cell_classifier/learn/
    eval_path: ./data/psl/cell_classifier/eval/
    cell_classifier_name: psl-cell-classifier-dg

block_extractor:
    rule_file: ./block_extractor/psl/psl-block-extractor-v2.psl
    learned_rule_file: ./block_extractor/psl/psl-block-extractor-v2-learned.psl
    predicate_file: ./block_extractor/psl/psl-block-extractor-v2-predicates.txt
    learn_path: ./data/psl/block_extractor/learn/
    eval_path: ./data/psl/block_extractor/eval/
    block_extractor_name: psl-block-extractor-dg

layout_detector:
    class: ./layout_detector.layout_detector_psl.LayoutDetectorPSL
    rule_file: ./layout_detector/psl/psl-layout-detector.psl
    learned_rule_file: ./layout_detector/psl/psl-layout-detector-learned.psl
    predicate_file: ./layout_detector/psl/psl-layout-detector-predicates.txt
    learn_path: ./data/psl/layout_detector/learn/
    eval_path: ./data/psl/layout_detector/eval/
    layout_detector_name: psl-layout-detector-dg
